name 'nexus'
maintainer 'Richard Nixon'
maintainer_email 'richard.nixon@btinternet.com'
license 'Apache-2.0'
description 'Installs and configures Sonatype Nexus Repository Manager OSS'
version '0.1.0'
chef_version '>= 16.0'

supports 'ubuntu'
supports 'debian'
supports 'centos'
supports 'redhat'
supports 'almalinux'
supports 'rockylinux'
supports 'oracle'
supports 'amazon'
supports 'fedora'

issues_url 'https://github.com/trickyearlobe-cookbooks/nexus/issues'
source_url 'https://github.com/trickyearlobe-cookbooks/nexus'
